version: '3'

services:
    backend:
        depends_on:
            db:
                condition: service_started
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_CONFIGURATION: Development
        ports:
            - "5050:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: DockerTesting
            ASPNETCORE_HTTP_PORTS: 8080
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: RollerCoaster
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local