version: '3'

services:
    backend:
        depends_on:
            db:
                condition: service_started
            minio:
                condition: service_started
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_CONFIGURATION: Development
        ports:
            - "5050:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: DockerTesting
            ASPNETCORE_HTTP_PORTS: 8080
    db:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: RollerCoaster
        volumes:
            - db:/var/lib/postgresql/data
    minio:
        image: minio/minio:latest
        command: server --console-address ":7071" /data/
        ports:
            - "7070:9000"
            - "7071:7071"
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: rootrootroot
            MINIO_DEFAULT_BUCKETS: images
        volumes:
            - minio-storage:/data
    minio-mc:
        image: minio/mc
        depends_on:
            minio:
                condition: service_started
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set 'myminio' 'http://minio:9000' 'root' 'rootrootroot';
            /usr/bin/mc mb myminio/images;
            /usr/bin/mc anonymous set download myminio/images;
            "
volumes:
    db:
        driver: local
    minio-storage:
        driver: local